export const formTemplates = {
  "form-i": {
    title: "Project Proposal (Form - I)",
    description: "R&D project proposal for coal sector research and development",
    fields: [
      {
        name: "projectTitle",
        label: "1. Project Title",
        type: "text",
        required: true,
      },
      {
        name: "implementingAgency",
        label: "2. Name and Address of Principal Implementing Agency(s)",
        type: "textarea",
        required: true,
      },
      {
        name: "projectLeader",
        label: "Name of Project Leader/Coordinator/Principal Investigator",
        type: "text",
        required: true,
      },
      {
        name: "subImplementingAgency",
        label: "3. Name and Address of Sub-Implementing Agency(s)",
        type: "textarea",
        required: true,
      },
      {
        name: "coInvestigator",
        label: "Name of Co-Investigator(s)",
        type: "text",
        required: true,
      },
      {
        name: "issueDefinition",
        label: "4. Definition of the Issue (Max. 300 words)",
        type: "textarea",
        required: true,
      },
      {
        name: "objectives",
        label: "5. Objectives (Specific, not more than 2–3)",
        type: "textarea",
        required: true,
      },
      {
        name: "justification",
        label: "6. Justification for Subject Area (Max. 200 words)",
        type: "textarea",
        required: true,
      },
      {
        name: "benefitToIndustry",
        label: "7. How the Project is Beneficial to Coal Industry",
        type: "textarea",
        required: true,
      },
      {
        name: "workPlan",
        label: "8. Work Plan (Max. 100 words)",
        type: "textarea",
        required: true,
      },
      {
        name: "methodology",
        label: "8.1 Methodology (Max. 200 words)",
        type: "textarea",
        required: true,
      },
      {
        name: "organizationOfWork",
        label: "8.2 Organization of Work Elements (Max. 200 words)",
        type: "textarea",
        required: true,
      },
      {
        name: "timeSchedule",
        label: "8.3 Time Schedule of Activities and Milestones (Attach Bar/Pert Chart)",
        type: "file",
        required: true,
      },
      {
        name: "proposedOutlay",
        label: "9. Details of Proposed Outlay (₹ in Lakhs)",
        type: "table",
        columns: ["Item", "1st Year", "2nd Year", "3rd Year", "Total Cost"],
        required: true,
      },
      {
        name: "foreignExchange",
        label: "Foreign Exchange Component (if any)",
        type: "textarea",
        required: true,
      },
      {
        name: "fundPhasing",
        label: "10. Phasing of Fund Requirement (in % with respect to milestones)",
        type: "textarea",
        required: true,
      },
      {
        name: "landBuildingOutlay",
        label: "11. Outlay for Land & Building (₹ in Lakhs)",
        type: "table",
        columns: ["Item", "Plinth Area", "Type of Building", "Estimated Cost"],
        required: true,
      },
      {
        name: "landBuildingJustification",
        label: "12. Justification for Land & Building",
        type: "textarea",
        required: true,
      },
      {
        name: "equipmentOutlay",
        label: "13. Outlay for Equipment",
        type: "table",
        columns: [
          "Generic Name of Equipment",
          "Specifications",
          "Number",
          "Imported/Indigenous",
          "Estimated Cost (₹ in Lakhs)",
          "Foreign Exchange Component",
        ],
        required: true,
      },
      {
        name: "equipmentJustification",
        label: "14. Justification for Equipment",
        type: "textarea",
        required: true,
      },
      {
        name: "consumableOutlay",
        label: "15. Outlay for Consumable Materials",
        type: "table",
        columns: [
          "Head",
          "1st Year (₹)",
          "2nd Year (₹)",
          "3rd Year (₹)",
          "Total (₹)",
          "Foreign Exchange Component",
        ],
        required: true,
      },
      {
        name: "curriculumVitae",
        label: "16. Curriculum Vitae of Project Proponents",
        type: "file",
        required: true,
      },
      {
        name: "pastExperience",
        label: "17. Past Experience and Institutional Expertise",
        type: "textarea",
        required: true,
      },
      {
        name: "otherDetails",
        label: "18. Other Details (DGMS discussions, Literature Survey, R&D components, etc.)",
        type: "textarea",
        required: false,
      },
      {
        name: "videoLink",
        label: "19. Video Pitch (Add a YouTube video link for your 3-minute presentation)",
        type: "text",
        required: true,
      },
    ],
  },
  "form-ia": {
    title: "Endorsement from Head of Institution (Form - IA)",
    description: "Endorsement from Head of the Institution / Organisation",
    fields: [
      {
        name: "headName",
        label: "Head of Institution Name",
        type: "text",
        required: true,
      },
      {
        name: "headDesignation",
        label: "Designation",
        type: "text",
        required: true,
      },
      {
        name: "institutionName",
        label: "Institution Name",
        type: "text",
        required: true,
      },
      {
        name: "endorsementDate",
        label: "Endorsement Date",
        type: "date",
        required: true,
      },
      { name: "remarks", label: "Remarks", type: "textarea", required: true },
    ],
  },
};
